### ISSUE TITLE
iframing

### ISSUE THREAD

**Issue by JoshSack-CXT** [hlxsites/investsec-revego#39]
For the podcast news page the business have picked up the hyperlinked iframes for each of the recordings, how can these be iframed using a word doc as opposed to hyperlinked?

**Comment by fe-lix-** [comment]
The problem was due to the fact that not all index were published and that there was two podcast page. This is the correct podcast page with the correct iFrame being displayed : https://main--investsec-revego--hlxsites.hlx.page/news/the-revego-podcast-series
